"""
inject_notebook_docs.py
Inserts Markdown documentation cells into the Enhanced XGBoost notebook.
Run from the repo root:  python scripts/inject_notebook_docs.py
"""

import json

NB_PATH = r"e:\IIT\IRP\notebooks\05 - Enhanced - XGBoost.ipynb"


def md(cell_id: str, lines: list[str]) -> dict:
    """Return a Markdown notebook cell."""
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": lines,
    }


# ---------------------------------------------------------------------------
# Documentation cells
# ---------------------------------------------------------------------------

DOCS = {
    # ---- Title ----
    "cc2cc096": md("doc-title", [
        "# Enhanced XGBoost Classifier for In-Hospital Mortality Prediction\n",
        "\n",
        "This notebook trains an **enhanced XGBoost classifier** that augments the baseline\n",
        "clinical feature set with an NLP-derived risk score from a fine-tuned language model.\n",
        "The combined feature vector is used to predict in-hospital mortality (MIMIC-IV).\n",
        "\n",
        "## Pipeline Overview\n",
        "1. Load pre-processed clinical features and labels.\n",
        "2. Integrate the NLP fine-tuned risk score as an additional feature.\n",
        "3. Split data into stratified 80 / 20 train-test sets.\n",
        "4. Train an XGBoost classifier with class-imbalance compensation.\n",
        "5. Evaluate performance (AUC-ROC, F1, classification report).\n",
        "6. Visualise the confusion matrix, ROC curve, and feature importances.\n",
        "7. Optimise the classification threshold via the Precision-Recall curve.",
    ]),

    # ---- Imports ----
    "5e2c5c5c": md("doc-imports", [
        "## 1. Imports\n",
        "\n",
        "Load all required libraries:\n",
        "- **pandas / numpy** – data manipulation.\n",
        "- **sklearn** – splitting utilities and evaluation metrics.\n",
        "- **xgboost** – the gradient-boosted-tree classifier.\n",
        "- **matplotlib / seaborn** – visualisation.\n",
        "- **core utilities** – project helpers for saving models, reports, and figures.",
    ]),

    # ---- Load base features ----
    "e26925c4": md("doc-load-data", [
        "## 2. Load Pre-Processed Clinical Features\n",
        "\n",
        "Load the feature matrix `X`, binary label vector `y` (0 = Survivor, 1 = Mortality),\n",
        "and feature names from `.npy` files produced by the preprocessing pipeline.",
    ]),

    # ---- Load NLP scores (head) ----
    "9ea5f2ea": md("doc-nlp-scores", [
        "## 3. Load NLP Fine-Tuned Risk Scores\n",
        "\n",
        "Load the per-admission NLP risk scores generated by the fine-tuned clinical language model.\n",
        "The CSV file maps each hospital admission (`hadm_id`) to a continuous risk score in [0, 1].",
    ]),

    # ---- Extract column ----
    "09026320": md("doc-extract-scores", [
        "### 3a. Extract Risk Score Column\n",
        "\n",
        "Isolate the `nlp_finetuned_risk_score` column and reshape it into a 2-D column\n",
        "vector so it can be horizontally stacked onto the existing feature matrix.",
    ]),

    # ---- Combine features ----
    "9b09a4c5": md("doc-combine", [
        "### 3b. Augment Feature Matrix with NLP Score\n",
        "\n",
        "Horizontally concatenate the NLP risk score to the clinical feature matrix\n",
        "and update the feature-name list, producing the **final 22-feature input matrix**.",
    ]),

    # ---- Feature set summary ----
    "0f0da698": md("doc-feature-info", [
        "### 3c. Feature Set Summary\n",
        "\n",
        "Print the total number of features in the augmented matrix and identify\n",
        "column indices that correspond to NLP-derived features (prefix `nlp_`).",
    ]),

    # ---- Train / test split ----
    "ad534a6b": md("doc-split", [
        "## 4. Train / Test Split\n",
        "\n",
        "Partition the augmented dataset into training (80 %) and test (20 %) sets.\n",
        "`stratify=y` preserves the class distribution in both splits, which is critical\n",
        "given the heavily imbalanced mortality labels.",
    ]),

    # ---- Model definition ----
    "42cf79bb": md("doc-model", [
        "## 5. Define XGBoost Classifier\n",
        "\n",
        "Instantiate `XGBClassifier` with:\n",
        "- `scale_pos_weight=10` – compensates for the ~10:1 Survivor:Mortality imbalance.\n",
        "- `eval_metric='logloss'` – log-loss evaluation during training.\n",
        "- `random_state=42` – for reproducibility.",
    ]),

    # ---- Train ----
    "98220c7b": md("doc-train", [
        "## 6. Train the Model\n",
        "\n",
        "Fit the XGBoost classifier on the training split and persist the trained model\n",
        "to disk via the project-level `save_model` utility.",
    ]),

    # ---- Predict ----
    "27266bff": md("doc-predict", [
        "## 7. Generate Predictions\n",
        "\n",
        "Produce hard class predictions (`y_pred`) and probability scores (`y_prob`)\n",
        "for the positive (Mortality) class on the held-out test set.",
    ]),

    # ---- Compute metrics ----
    "faed1cad": md("doc-metrics", [
        "## 8. Compute Evaluation Metrics\n",
        "\n",
        "Calculate:\n",
        "- **AUC-ROC** – area under the receiver operating characteristic curve.\n",
        "- **F1-Score** – harmonic mean of precision and recall for the minority class.\n",
        "- **Classification Report** – per-class precision, recall, and F1.",
    ]),

    # ---- Print / save report ----
    "aa5599ca": md("doc-print-report", [
        "### 8a. Print and Save Metrics\n",
        "\n",
        "Display evaluation results and persist the classification report to disk.",
    ]),

    # ---- Confusion matrix ----
    "ad0dea7d": md("doc-cm", [
        "## 9. Confusion Matrix\n",
        "\n",
        "Plot and save a heatmap of the confusion matrix to visualise\n",
        "TP, FP, TN, and FN counts.",
    ]),

    # ---- ROC curve ----
    "7f93476f": md("doc-roc", [
        "## 10. ROC Curve\n",
        "\n",
        "Plot and save the Receiver Operating Characteristic (ROC) curve.\n",
        "The diagonal dashed line represents a random classifier (AUC = 0.5).",
    ]),

    # ---- Threshold optimisation ----
    "3657157f": md("doc-thresh", [
        "## 11. Threshold Optimisation\n",
        "\n",
        "Use the Precision-Recall curve to find the threshold that maximises F1-score\n",
        "on the test set. A standard 0.5 threshold is typically suboptimal for\n",
        "heavily imbalanced datasets.",
    ]),

    # ---- Feature importances ----
    "0e1f58ea": md("doc-feat-imp", [
        "## 12. Feature Importances\n",
        "\n",
        "Plot and save a bar chart of XGBoost feature importances (gain-based) to\n",
        "identify which clinical and NLP features drive the predictions most.",
    ]),
}

# ---------------------------------------------------------------------------
# Inject into notebook
# ---------------------------------------------------------------------------

with open(NB_PATH, "r", encoding="utf-8") as fh:
    nb = json.load(fh)

new_cells: list[dict] = []
for cell in nb["cells"]:
    cid = cell.get("id", "")
    if cid in DOCS:
        new_cells.append(DOCS[cid])
    new_cells.append(cell)

nb["cells"] = new_cells

with open(NB_PATH, "w", encoding="utf-8") as fh:
    json.dump(nb, fh, indent=1, ensure_ascii=False)

print(f"Done – inserted {len(DOCS)} documentation cells into {NB_PATH}")
